In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

In [2]:
import sys
sys.path.insert(1, 'C:/Users/pnknv/Documents/GitHub/yadisk_loader')
from main_utils import *

In [3]:
ssh_host, ssh_port, ssh_username, ssh_password, \
database_username, database_password, database_name, \
localhost, localhost_port, table_name, ya_token, ya_api, ya_link = get_config()

In [4]:
sql_server, sql_engine = get_sql_engine()

In [5]:
ssh_host

'92.53.64.66'

In [6]:
database_name

'app_nedvizhka_db'

# read table dev

In [ ]:
av_old = pd.read_csv('saved_data/avito_dadata_request_2023_05_16.csv', encoding='cp1251', index_col=0)

In [ ]:
av = pd.read_csv('saved_data/avito_dadata_request_2023_06_05.csv', encoding='cp1251', index_col=0)

In [42]:
av_old

,house_fias_id,data,geo_lat,geo_lon,street,house,qc,result,qc_geo,ad_id
0,fed386f5-8c41-400c-95fb-d217fdac5f1b,{'source': 'Новороссийск; Приморский район; се...,44.740836,37.702014,Центральная,54,0,"Краснодарский край, г Новороссийск, с Цемдолин...",0,2998490461
1,f087bb64-cdd9-46bd-a87e-fb72653121e2,{'source': 'Новороссийск; Волгоградская ул.; 4...,44.684836,37.776623,Волгоградская,48,0,"Краснодарский край, г Новороссийск, ул Волгогр...",0,3009536003
2,7b5b5943-333d-4806-832c-41128b2ff9d0,{'source': 'Новороссийск; ул. Алексея Матвейки...,44.675753,37.776537,Имени Алексея Матвейкина,4,0,"Краснодарский край, г Новороссийск, ул Имени А...",0,2972555799
3,3d40ae4a-a76e-4fe2-8a79-44487502e4ce,{'source': 'Новороссийск; Краснодарский край; ...,44.676063,37.784342,Южная,11,0,"Краснодарский край, г Новороссийск, ул Южная, ...",0,2502487256
4,8ea664bb-42b3-48b7-9e51-0d7e36431fa9,{'source': 'Новороссийск; Октябрьская ул.; 1к2...,44.713977,37.767499,Октябрьская,1,0,"Краснодарский край, г Новороссийск, ул Октябрь...",1,2869806020
...,...,...,...,...,...,...,...,...,...,...
1248,NaN,{'source': 'Новосибирск; ул. Большевистская; с...,54.992263,82.978619,Большевистская,14,0,"г Новосибирск, ул Большевистская, стр 14",2,3015160080
1249,NaN,{'source': 'Новосибирск; ул. Большевистская; с...,54.992263,82.978619,Большевистская,14,0,"г Новосибирск, ул Большевистская, стр 14",2,3014940800
1250,NaN,{'source': 'Новосибирск; пр-т Красный; стр. 23...,55.062880,82.911833,Красный,236,0,"г Новосибирск, пр-кт Красный, стр 236",2,3040467641
1251,NaN,{'source': 'Новосибирск; пр-т Красный; стр. 23...,55.062880,82.911833,Красный,236,0,"г Новосибирск, пр-кт Красный, стр 236",2,3040473014
1252,NaN,{'source': 'Новосибирск; ул. Никитина; стр. 4'...,55.021646,82.971932,Никитина,4,0,"г Новосибирск, ул Никитина, стр 4",2,2893712938

In [43]:
av

,house_fias_id,data,geo_lat,geo_lon,street,house,qc,result,qc_geo,ad_id,addr
0,b289ef21-0479-4e34-8636-7d6acdbe5f20,"{'source': 'Новороссийск; ул. Мира; 17', 'resu...",44.722364,37.775825,Мира,17,0.0,"Краснодарский край, г Новороссийск, ул Мира, д 17",0.0,3023595653,Новороссийск; ул. Мира; 17
1,fed386f5-8c41-400c-95fb-d217fdac5f1b,{'source': 'Новороссийск; Приморский район; се...,44.740836,37.702014,Центральная,54,0.0,"Краснодарский край, г Новороссийск, с Цемдолин...",0.0,3036036118,Новороссийск; Приморский район; село Цемдолина...
2,5373c9fb-07e6-470f-aebf-bd0d3eab833e,{'source': 'Новороссийск; Приморский район; се...,44.756609,37.722575,Красина,53,0.0,"Краснодарский край, г Новороссийск, с Цемдолин...",2.0,2519132585,Новороссийск; Приморский район; село Цемдолина...
3,1369b75f-7420-4b12-b352-d1ed89251b47,"{'source': 'Новороссийск; ул. Котанова; 2', 'r...",44.673480,37.768978,Котанова,2,0.0,"Краснодарский край, г Новороссийск, ул Котанов...",2.0,2478056149,Новороссийск; ул. Котанова; 2
4,5373c9fb-07e6-470f-aebf-bd0d3eab833e,{'source': 'Новороссийск; с. Цемдолина; ул. Кр...,44.756609,37.722575,Красина,53,0.0,"Краснодарский край, г Новороссийск, с Цемдолин...",2.0,2430225103,Новороссийск; с. Цемдолина; ул. Красина; д. 53
...,...,...,...,...,...,...,...,...,...,...,...
2739,04794fbf-ed0e-4026-a982-0f3f84079bed,{'source': 'Новосибирск; ул. Авиастроителей; д...,55.070006,82.966656,Авиастроителей,1А,0.0,"г Новосибирск, ул Авиастроителей, д 1А",0.0,3047687584,Новосибирск; ул. Авиастроителей; д. 1А
2740,04794fbf-ed0e-4026-a982-0f3f84079bed,{'source': 'Новосибирск; ул. Авиастроителей; д...,55.070006,82.966656,Авиастроителей,1А,0.0,"г Новосибирск, ул Авиастроителей, д 1А",0.0,3046973785,Новосибирск; ул. Авиастроителей; д. 1А
2742,NaN,{'source': 'Новосибирск; р-н Первомайский; ул....,54.976652,83.085739,Виноградова,3,0.0,"г Новосибирск, ул Виноградова, д 3",2.0,3021183121,Новосибирск; р-н Первомайский; ул. Виноградова...
2743,NaN,{'source': 'Новосибирск; р-н Первомайский; ул....,54.976652,83.085739,Виноградова,3,0.0,"г Новосибирск, ул Виноградова, д 3",2.0,3021286755,Новосибирск; р-н Первомайский; ул. Виноградова...
2744,NaN,{'source': 'Новосибирск; р-н Первомайский; ул....,54.976652,83.085739,Виноградова,3,0.0,"г Новосибирск, ул Виноградова, д 3",2.0,3021746351,Новосибирск; р-н Первомайский; ул. Виноградова...

In [9]:
av['city'] = av.addr.apply(lambda x: x.split('; ')[0])

In [10]:
av.city.value_counts()

Новосибирск     1809
Казань           536
Новороссийск     128
Name: city, dtype: int64

In [11]:
len(av[av.city == 'Казань'].addr.unique())

298

In [12]:
av

,house_fias_id,data,geo_lat,geo_lon,street,house,qc,result,qc_geo,ad_id,addr,city
0,b289ef21-0479-4e34-8636-7d6acdbe5f20,"{'source': 'Новороссийск; ул. Мира; 17', 'resu...",44.722364,37.775825,Мира,17,0.0,"Краснодарский край, г Новороссийск, ул Мира, д 17",0.0,3023595653,Новороссийск; ул. Мира; 17,Новороссийск
1,fed386f5-8c41-400c-95fb-d217fdac5f1b,{'source': 'Новороссийск; Приморский район; се...,44.740836,37.702014,Центральная,54,0.0,"Краснодарский край, г Новороссийск, с Цемдолин...",0.0,3036036118,Новороссийск; Приморский район; село Цемдолина...,Новороссийск
2,5373c9fb-07e6-470f-aebf-bd0d3eab833e,{'source': 'Новороссийск; Приморский район; се...,44.756609,37.722575,Красина,53,0.0,"Краснодарский край, г Новороссийск, с Цемдолин...",2.0,2519132585,Новороссийск; Приморский район; село Цемдолина...,Новороссийск
3,1369b75f-7420-4b12-b352-d1ed89251b47,"{'source': 'Новороссийск; ул. Котанова; 2', 'r...",44.673480,37.768978,Котанова,2,0.0,"Краснодарский край, г Новороссийск, ул Котанов...",2.0,2478056149,Новороссийск; ул. Котанова; 2,Новороссийск
4,5373c9fb-07e6-470f-aebf-bd0d3eab833e,{'source': 'Новороссийск; с. Цемдолина; ул. Кр...,44.756609,37.722575,Красина,53,0.0,"Краснодарский край, г Новороссийск, с Цемдолин...",2.0,2430225103,Новороссийск; с. Цемдолина; ул. Красина; д. 53,Новороссийск
...,...,...,...,...,...,...,...,...,...,...,...,...
2739,04794fbf-ed0e-4026-a982-0f3f84079bed,{'source': 'Новосибирск; ул. Авиастроителей; д...,55.070006,82.966656,Авиастроителей,1А,0.0,"г Новосибирск, ул Авиастроителей, д 1А",0.0,3047687584,Новосибирск; ул. Авиастроителей; д. 1А,Новосибирск
2740,04794fbf-ed0e-4026-a982-0f3f84079bed,{'source': 'Новосибирск; ул. Авиастроителей; д...,55.070006,82.966656,Авиастроителей,1А,0.0,"г Новосибирск, ул Авиастроителей, д 1А",0.0,3046973785,Новосибирск; ул. Авиастроителей; д. 1А,Новосибирск
2742,NaN,{'source': 'Новосибирск; р-н Первомайский; ул....,54.976652,83.085739,Виноградова,3,0.0,"г Новосибирск, ул Виноградова, д 3",2.0,3021183121,Новосибирск; р-н Первомайский; ул. Виноградова...,Новосибирск
2743,NaN,{'source': 'Новосибирск; р-н Первомайский; ул....,54.976652,83.085739,Виноградова,3,0.0,"г Новосибирск, ул Виноградова, д 3",2.0,3021286755,Новосибирск; р-н Первомайский; ул. Виноградова...,Новосибирск
2744,NaN,{'source': 'Новосибирск; р-н Первомайский; ул....,54.976652,83.085739,Виноградова,3,0.0,"г Новосибирск, ул Виноградова, д 3",2.0,3021746351,Новосибирск; р-н Первомайский; ул. Виноградова...,Новосибирск

# creating rep

In [13]:
files = os.listdir('saved_data/')

In [14]:
files_avito = [i for i in files if 'cian' not in i]
files_cian = [i for i in files if 'cian' in i]

In [15]:
files_avito = sorted(files_avito, key=lambda x: datetime.strptime(x[21:31], '%Y_%m_%d'))
files_cian = sorted(files_cian, key=lambda x: datetime.strptime(x[20:30], '%Y_%m_%d'))

In [16]:
files_avito

['avito_dadata_request_2023_06_01.csv',
 'avito_dadata_request_2023_06_05.csv',
 'avito_dadata_request_2023_06_06.csv',
 'avito_dadata_request_2023_06_07.csv']

In [17]:
files_cian

['cian_dadata_request_2023_06_01.csv',
 'cian_dadata_request_2023_06_05.csv',
 'cian_dadata_request_2023_06_06.csv',
 'cian_dadata_request_2023_06_07.csv']

In [18]:
def get_city_house_cnt(engine):
    city_house_cnt_query = f'''SELECT c.name as city, count(*) as house_cnt
                    from jkh_houses jh 
                    join city c 
                    on c.id = jh.city_id 
                    GROUP by jh.city_id
                    '''
    try:
        con_obj = engine.connect()
        city_house_cnt_db = pd.read_sql(text(city_house_cnt_query), con=con_obj)
        con_obj.close()
        exc_code = None
    except:
        city_house_cnt_db = None
        exc_code = exc.code
    return city_house_cnt_db, exc_code

In [19]:
city_cnt_df, erc = get_city_house_cnt(engine=sql_engine)

In [20]:
city_cnt_df

                city  house_cnt
0        Владивосток       3576
1          Краснодар      13915
2               Сочи       4515
3       Новороссийск       3440
4              Анапа        787
5            Армавир       1518
6          Челябинск      13229
7       Магнитогорск       2841
8              Миасс       1063
9            Копейск       1917
10          Златоуст       1334
11            Казань      11968
12  Набережные Челны       1333
13        Нижнекамск        810
14       Альметьевск       1083
15      Зеленодольск        612
16             Томск       3757
17       Новосибирск       8631
18           Саратов       6407
19       Калининград       6526

In [21]:
files_parse = os.listdir('saved_shit/')

In [22]:
files_parse_avito = [i for i in files_parse if 'циан' not in i]
files_parse_cian = [i for i in files_parse if 'циан' in i]

In [23]:
files_parse_df = pd.DataFrame(columns=['f_name', 'f_date', 'source'])

In [24]:
for i in files_parse_avito:
    files_parse_df.loc[len(files_parse_df)] = [i, None, 'avito']

In [25]:
for i in files_parse_cian:
    files_parse_df.loc[len(files_parse_df)] = [i, None, 'cian']

In [26]:
files_parse_df.f_date = files_parse_df.f_name.apply(lambda x: datetime.strptime(x[-25:-17], '%d-%m-%y'))

In [27]:
def get_source(rep_dt, source):
    if source == 'avito':
        source_name = files_parse_df[(files_parse_df.f_date == rep_dt) & 
                                     (files_parse_df.source == source)].f_name.values[0]
        
        city_df, source_df, exc_code = get_tables_info(sql_engine)
        city_df_dict = city_df.set_index('id').to_dict()['url_avito']
        
        df_s = pd.read_csv(f'saved_shit/{source_name}', delimiter=';')
        
        df_s['ad_id'] = df_s['Ссылка'].apply(lambda x: x.split('_')[-1])
        df_s['ad_id'] = df_s['ad_id'].astype('int64')
        df_s['city'] = df_s['Ссылка'].apply(lambda x: x.split('/')[3])
        df_s['city_id'] = df_s['city'].apply(lambda x: city_id_from_link(x, city_df_dict))
        df_s['addr'] = df_s.apply(lambda row: avito_addr_from_row(row, city_df), axis=1)
        df_s['city_ru'] = df_s.addr.apply(lambda x: x.split('; ')[0])
        
        return df_s
        
    else:
        source_name = files_parse_df[(files_parse_df.f_date == rep_dt) & 
                                     (files_parse_df.source == source)].f_name.values[0]
        
        city_df, source_df, exc_code = get_tables_info(sql_engine)
        city_df_dict = city_df.set_index('id').to_dict()['name']
        
        df_c = pd.read_csv(f'saved_shit/{source_name}', delimiter=',')
        
        df_c['ad_id'] = df_c['Ссылка'].apply(lambda x: x.split('/')[-2])
        df_c['ad_id'] = df_c['ad_id'].astype('int64')
        df_c['city'] = df_c['Адрес'].apply(lambda x: x.split(';')[1])
        df_c['city_id'] = df_c['city'].apply(lambda x: city_id_from_link(x, city_df_dict))
        df_c['addr'] = df_c['Адрес']
        
        return df_c

# avito rep

In [28]:
from tqdm import tqdm

In [29]:
rep_table = pd.DataFrame(columns=['dt', 'city', 'source', 'house_cnt', 'ad_cnt', 'ad_new_cnt', 
                                  'addr_new_cnt', 'ddt_cnt', 'qc_0_cnt' , 'qc_not_0_cnt', 'fias_none_cnt'])

In [30]:
source = 'avito'
for av_file in tqdm(files_avito, total=len(files_avito)):
    file_date = datetime.strptime(av_file[21:31], '%Y_%m_%d')
    df = pd.read_csv(f'saved_data/{av_file}', encoding='cp1251', index_col=0)
    df['city'] = df.addr.apply(lambda x: x.split('; ')[0])
    
    city_list = df.city.unique().tolist()
    
    print('get source', file_date)
    df_source = get_source(file_date, source)
    
    for city_name in city_list:
        city = city_name
        house_cnt = city_cnt_df[city_cnt_df.city==city_name]['house_cnt'].values[0]
        ad_cnt = len(df_source[df_source.city_ru == city].ad_id.unique())
        
        ad_new_cnt = len(df[df.city == city_name])
        addr_new_cnt = len(df[df.city == city_name].addr.unique())
        ddt_cnt = len(df[df.city == city_name].addr.unique()) # в dadata result сохраняются только успешные запросы 
        
        df_unique = df.drop_duplicates(subset='addr')
        
        qc_0_cnt = len(df_unique[(df_unique.city == city_name) & (df_unique.qc == 0.0)])
        qc_not_0_cnt = len(df_unique[(df_unique.city == city_name) & (df_unique.qc != 0.0)])
        fias_none_cnt = len(df_unique[(df_unique.city == city_name) & (df_unique.house_fias_id.isna())])
        
        to_append = [file_date, city, source, house_cnt, ad_cnt, ad_new_cnt, addr_new_cnt, 
                     ddt_cnt, qc_0_cnt, qc_not_0_cnt, fias_none_cnt]
        rep_table.loc[len(rep_table)] = to_append

  0%|                                                                                            | 0/4 [00:00<?, ?it/s]

get source 2023-06-01 00:00:00

 25%|█████████████████████                                                               | 1/4 [00:38<01:56, 38.97s/it]

get source 2023-06-05 00:00:00

 50%|██████████████████████████████████████████                                          | 2/4 [01:19<01:20, 40.08s/it]

get source 2023-06-06 00:00:00

 75%|███████████████████████████████████████████████████████████████                     | 3/4 [01:56<00:38, 38.68s/it]

get source 2023-06-07 00:00:00

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:36<00:00, 39.03s/it]

# cian rep

In [34]:
rep_table_cian = pd.DataFrame(columns=['dt', 'city', 'source', 'house_cnt', 'ad_cnt', 'ad_new_cnt', 
                                  'addr_new_cnt', 'ddt_cnt', 'qc_0_cnt' , 'qc_not_0_cnt', 'fias_none_cnt'])

In [35]:
source = 'cian'
for c_file in tqdm(files_cian, total=len(files_cian)):
    file_date = datetime.strptime(c_file[20:30], '%Y_%m_%d')
    df = pd.read_csv(f'saved_data/{c_file}', encoding='cp1251', index_col=0)
    df['city'] = df.addr.apply(lambda x: x.split('; ')[1])
    df = df[df.city.isin(city_cnt_df.city.to_list())]
    
    city_list = df.city.unique().tolist()
    
    print('get source', file_date)
    df_source = get_source(file_date, source)
    
    for city_name in city_list:
        city = city_name
        house_cnt = city_cnt_df[city_cnt_df.city==city_name]['house_cnt'].values[0]
        ad_cnt = len(df_source[df_source.city == city].ad_id.unique())
        
        ad_new_cnt = len(df[df.city == city_name])
        addr_new_cnt = len(df[df.city == city_name].addr.unique())
        ddt_cnt = len(df[df.city == city_name].addr.unique()) # в dadata result сохраняются только успешные запросы 
        
        df_unique = df.drop_duplicates(subset='addr')
        
        qc_0_cnt = len(df_unique[(df_unique.city == city_name) & (df_unique.qc == 0.0)])
        qc_not_0_cnt = len(df_unique[(df_unique.city == city_name) & (df_unique.qc != 0.0)])
        fias_none_cnt = len(df_unique[(df_unique.city == city_name) & (df_unique.house_fias_id.isna())])
        
        to_append = [file_date, city, source, house_cnt, ad_cnt, ad_new_cnt, addr_new_cnt, 
                     ddt_cnt, qc_0_cnt, qc_not_0_cnt, fias_none_cnt]
        rep_table_cian.loc[len(rep_table_cian)] = to_append

  0%|                                                                                            | 0/4 [00:00<?, ?it/s]

get source 2023-06-01 00:00:00

 25%|█████████████████████                                                               | 1/4 [00:02<00:06,  2.20s/it]

get source 2023-06-05 00:00:00

 50%|██████████████████████████████████████████                                          | 2/4 [00:04<00:04,  2.10s/it]

get source 2023-06-06 00:00:00

 75%|███████████████████████████████████████████████████████████████                     | 3/4 [00:06<00:02,  2.06s/it]

get source 2023-06-07 00:00:00

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:08<00:00,  2.04s/it]

In [36]:
rep_table_cian

,dt,city,source,house_cnt,ad_cnt,ad_new_cnt,addr_new_cnt,ddt_cnt,qc_0_cnt,qc_not_0_cnt,fias_none_cnt
0,2023-06-01,Сочи,cian,4515,23722,1243,576,576,382,194,124
1,2023-06-01,Новороссийск,cian,3440,5011,294,93,93,83,10,9
2,2023-06-01,Новосибирск,cian,8631,20676,1946,1221,1221,443,778,300
3,2023-06-01,Челябинск,cian,13229,4623,181,96,96,90,6,9
4,2023-06-01,Краснодар,cian,13915,30630,1426,403,403,267,136,63
5,2023-06-01,Казань,cian,11968,10432,508,407,407,119,288,69
6,2023-06-01,Калининград,cian,6526,5553,602,432,432,376,56,9
7,2023-06-01,Томск,cian,3757,4428,226,159,159,144,15,7
8,2023-06-01,Саратов,cian,6407,4951,972,667,667,624,43,32
9,2023-06-01,Анапа,cian,787,7081,301,129,129,109,20,24
10,2023-06-01,Армавир,cian,1518,86,5,5,5,5,0,0
11,2023-06-05,Краснодар,cian,13915,30562,678,181,181,115,66,39
12,2023-06-05,Казань,cian,11968,9867,128,117,117,33,84,25
13,2023-06-05,Сочи,cian,4515,23619,379,236,236,161,75,41
14,2023-06-05,Новосибирск,cian,8631,20663,585,401,401,144,257,145
15,2023-06-05,Челябинск,cian,13229,4497,63,42,42,41,1,6
16,2023-06-05,Томск,cian,3757,4367,39,32,32,29,3,4
17,2023-06-05,Новороссийск,cian,3440,5038,100,46,46,44,2,2
18,2023-06-05,Саратов,cian,6407,4881,250,230,230,216,14,17
19,2023-06-05,Калининград,cian,6526,4917,212,129,129,104,25,4
20,2023-06-05,Анапа,cian,787,7375,113,62,62,56,6,11
21,2023-06-05,Армавир,cian,1518,82,2,2,2,2,0,0
22,2023-06-05,Набережные Челны,cian,1333,1,1,1,1,1,0,0
23,2023-06-06,Челябинск,cian,13229,4684,22,15,15,15,0,3
24,2023-06-06,Казань,cian,11968,10318,78,68,68,22,46,18
25,2023-06-06,Краснодар,cian,13915,31720,415,107,107,67,40,28
26,2023-06-06,Новосибирск,cian,8631,21255,267,182,182,62,120,65
27,2023-06-06,Томск,cian,3757,4368,29,23,23,21,2,2
28,2023-06-06,Сочи,cian,4515,22612,185,137,137,94,43,23
29,2023-06-06,Новороссийск,cian,3440,5137,44,22,22,20,2,2
30,2023-06-06,Калининград,cian,6526,5821,93,56,56,50,6,5
31,2023-06-06,Саратов,cian,6407,5151,105,92,92,84,8,5
32,2023-06-06,Анапа,cian,787,7601,34,29,29,28,1,4
33,2023-06-07,Краснодар,cian,13915,28624,246,136,136,93,43,27
34,2023-06-07,Новосибирск,cian,8631,20452,242,167,167,63,104,70
35,2023-06-07,Сочи,cian,4515,21493,178,131,131,84,47,29
36,2023-06-07,Новороссийск,cian,3440,4983,36,17,17,16,1,2
37,2023-06-07,Саратов,cian,6407,4778,82,73,73,69,4,5
38,2023-06-07,Казань,cian,11968,9538,59,52,52,20,32,19
39,2023-06-07,Калининград,cian,6526,5398,73,51,51,41,10,2
40,2023-06-07,Челябинск,cian,13229,4499,23,16,16,15,1,2
41,2023-06-07,Анапа,cian,787,6846,45,31,31,26,5,8
42,2023-06-07,Томск,cian,3757,4164,16,15,15,12,3,2
43,2023-06-07,Армавир,cian,1518,81,1,1,1,1,0,0

In [46]:
rep_table.append(rep_table_cian, ignore_index=True).to_excel('new_stats.xlsx')