In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [2]:
import sys
sys.path.insert(1, 'C:/Users/pnknv/Documents/GitHub/yadisk_loader')
from main_utils import *

In [3]:
ssh_host, ssh_port, ssh_username, ssh_password, \
database_username, database_password, database_name, \
localhost, localhost_port, table_name, ya_token, ya_api, ya_link = get_config()

In [4]:
sql_server, sql_engine = get_sql_engine()

In [5]:
def get_exist_ad_id(engine, source):
    source_id = 2 if source == 'cian' else 3
    ad_id_query = f'SELECT ad_id FROM realty where source_id = {source_id}'
    try:
        con_obj = engine.connect()
        ad_id_db = pd.read_sql(text(ad_id_query), con=con_obj)
        con_obj.close()
        exc_code = None
    except Exception as exc:
        logging.error(traceback.format_exc())
        ad_id_db = None
        exc_code = exc.code
    return ad_id_db, exc_code

In [21]:
city_df, source_df, exc_code = get_tables_info(sql_engine)

# money

In [38]:
files = os.listdir('saved_shit/')

In [39]:
files_avito = [i for i in files if 'циан' not in i]
files_cian = [i for i in files if 'циан' in i]

In [29]:
city_df, source_df, exc_code = get_tables_info(sql_engine)

In [30]:
test_cian = pd.read_csv('saved_shit/' + files_cian[0], delimiter=',')

In [31]:
test_cian['ad_id'] = test_cian['Ссылка'].apply(lambda x: x.split('/')[-2])
test_cian['ad_id'] = test_cian['ad_id'].astype('int64')

In [32]:
city_df_dict = city_df.set_index('id').to_dict()['name']
test_cian['city'] = test_cian['Адрес'].apply(lambda x: x.split(';')[1])
test_cian['city_id'] = test_cian['city'].apply(lambda x: city_id_from_link(x, city_df_dict))

In [33]:
test_cian['addr'] = test_cian['Адрес']

In [19]:
test_cian

,Ссылка,Заголовок,Комнат,Площадь,Этаж,Цена,Цена за м2,Название жк,Адрес,Дата публикации,Тип продавца,Продавец,ad_id,city,city_id,addr
0,https://krasnodar.cian.ru/sale/flat/286046952/,"2-комн. кв., 70 м², 5/12 этаж",2-комн. кв.,70 м²,5/12 этаж,5700000,81429,ЖК «Парус»,Краснодарский край;Краснодар;Прикубанский;мкр....,"вчера (вчера, 12:55)",Агентство недвижимости,ЧФК-Недвижимость,286046952,Краснодар,2.0,Краснодарский край;Краснодар;Прикубанский;мкр....
1,https://krasnodar.cian.ru/sale/flat/286032732/,"2-комн. кв., 51,5 м², 2/10 этаж",2-комн. кв.,"51,5 м²",2/10 этаж,5700000,110680,NaN,Краснодарский край;Краснодар;Прикубанский;мкр....,"пять дней назад (25 апр, 18:22)",Агентство недвижимости,ЭТАЖИ-КУБАНЬ,286032732,Краснодар,2.0,Краснодарский край;Краснодар;Прикубанский;мкр....
2,https://krasnodar.cian.ru/sale/flat/286032730/,"1-комн. кв., 40 м², 7/22 этаж",1-комн. кв.,40 м²,7/22 этаж,5700000,142500,NaN,Краснодарский край;Краснодар;Прикубанский;улиц...,"пять дней назад (25 апр, 18:22)",Агентство недвижимости,ЭТАЖИ-КУБАНЬ,286032730,Краснодар,2.0,Краснодарский край;Краснодар;Прикубанский;улиц...
3,https://krasnodar.cian.ru/sale/flat/286029930/,"1-комн. кв., 47,8 м², 14/20 этаж",1-комн. кв.,"47,8 м²",14/20 этаж,5700000,119247,ЖК «Грани»,Краснодарский край;Краснодар;Прикубанский;улиц...,"2 недели назад (11 апр, 13:58)",Риелтор,ID 55338816,286029930,Краснодар,2.0,Краснодарский край;Краснодар;Прикубанский;улиц...
4,https://krasnodar.cian.ru/sale/flat/286020566/,"3-комн. кв., 66 м², 7/9 этаж",3-комн. кв.,66 м²,7/9 этаж,5700000,86364,ЖК «Sport Village»,Краснодарский край;Краснодар;Прикубанский;мкр....,"неделю назад (20 апр, 13:23)",Агентство недвижимости,Девелопмент-Юг,286020566,Краснодар,2.0,Краснодарский край;Краснодар;Прикубанский;мкр....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117291,https://sochi.cian.ru/sale/flat/277480315/,"3-комн. кв., 60 м², 2/11 этаж",3-комн. кв.,60 м²,2/11 этаж,13000000,216667,NaN,Краснодарский край;Сочи;р-н Центральный;мкр. Д...,"четыре дня назад (27 апр, 09:18)",Собственник,ID 94977241,277480315,Сочи,3.0,Краснодарский край;Сочи;р-н Центральный;мкр. Д...
117292,https://sochi.cian.ru/sale/flat/277459856/,"3-комн. кв., 101 м², 11/17 этаж",3-комн. кв.,101 м²,11/17 этаж,12300000,121782,NaN,Краснодарский край;Сочи;р-н Центральный;мкр. Ц...,"2 недели назад (13 апр, 13:54)",Агентство недвижимости,Черноморский проспект,277459856,Сочи,3.0,Краснодарский край;Сочи;р-н Центральный;мкр. Ц...
117293,https://sochi.cian.ru/sale/flat/277438444/,"Апартаменты-студия, 25 м², 4/5 этаж",Апартаменты-студия,25 м²,4/5 этаж,12500000,500000,NaN,Краснодарский край;Сочи;р-н Центральный;мкр. Ц...,"2 недели назад (17 апр, 17:58)",Риелтор,Виктор Захаров,277438444,Сочи,3.0,Краснодарский край;Сочи;р-н Центральный;мкр. Ц...
117294,https://sochi.cian.ru/sale/flat/277347516/,"Студия, 12 м², 4/4 этаж",Студия,12 м²,4/4 этаж,13000000,1083333,NaN,Краснодарский край;Сочи;р-н Центральный;мкр. Н...,"полгода назад (19 сен, 23:58)",Собственник,ID 93157894,277347516,Сочи,3.0,Краснодарский край;Сочи;р-н Центральный;мкр. Н...
117295,https://sochi.cian.ru/sale/flat/277334666/,"3-комн. кв., 93 м², 6/20 этаж",3-комн. кв.,93 м²,6/20 этаж,12900000,138710,NaN,Краснодарский край;Сочи;р-н Центральный;мкр. М...,"2 недели назад (11 апр, 19:04)",Агентство недвижимости,ID 53767050,277334666,Сочи,3.0,Краснодарский край;Сочи;р-н Центральный;мкр. М...

In [13]:
test_avito = pd.read_csv('saved_shit/' + files_avito[0], delimiter=';')

In [14]:
test_avito['ad_id'] = test_avito['Ссылка'].apply(lambda x: x.split('_')[-1])
test_avito['ad_id'] = test_avito['ad_id'].astype('int64')

In [15]:
city_df_dict = city_df.set_index('id').to_dict()['url_avito']
test_avito['city'] = test_avito['Ссылка'].apply(lambda x: x.split('/')[3])
test_avito['city_id'] = test_avito['city'].apply(lambda x: city_id_from_link(x, city_df_dict))

In [16]:
test_avito['addr'] = test_avito.apply(lambda row: avito_addr_from_row(row, city_df), axis=1)

In [17]:
test_avito

,Ссылка,Заголовок,Комнат,Площадь,Этаж,Цена,Цена за м2,Название жк,Район,Улица,Дата публикации,Тип продавца,Продавец,Ссылка на продавца,Завершённых объявлений,ad_id,city,city_id,addr
0,https://www.avito.ru/tomsk/kvartiry/apartament...,"Апартаменты-студия, 29 м², 5/5 эт.",Апартаменты-студия,29 м²,5/5 эт.,1975000,68103,NaN,р-н Ленинский,"микрорайон Черемошники, Кузнецкий пер., 5",12 часов назад,Частное лицо,NaN,NaN,NaN,3169985711,tomsk,17,Томск; р-н Ленинский; микрорайон Черемошники; ...
1,https://www.avito.ru/tomsk/kvartiry/1-k._kvart...,"1-к. квартира, 34,9 м², 4/6 эт.",1-к. квартира,"34,9 м²",4/6 эт.,3700000,106017,NaN,р-н Кировский,"ул. Матросова, 6",6 дней назад,Частное лицо,NaN,NaN,NaN,2739762184,tomsk,17,Томск; р-н Кировский; ул. Матросова; 6
2,https://www.avito.ru/tomsk/kvartiry/2-k._kvart...,"2-к. квартира, 36 м², 1/2 эт.",2-к. квартира,36 м²,1/2 эт.,2600000,72222,NaN,р-н Октябрьский,"ул. Мичурина, 99Ас4",22 часа назад,Агентство,ОФИС ПРОДАЖ «ЗАСТРОЙЩИКА»,https://www.avito.ru/user/c245de34b6855769043d...,388,2861453708,tomsk,17,Томск; р-н Октябрьский; ул. Мичурина; 99Ас4
3,https://www.avito.ru/tomsk/kvartiry/2-k._kvart...,"2-к. квартира, 37 м², 3/5 эт.",2-к. квартира,37 м²,3/5 эт.,3350000,90541,NaN,р-н Ленинский,"ул. Говорова, 18",4 часа назад,Частное лицо,NaN,NaN,NaN,2859068275,tomsk,17,Томск; р-н Ленинский; ул. Говорова; 18
4,https://www.avito.ru/tomsk/kvartiry/2-k._kvart...,"2-к. квартира, 44,8 м², 3/5 эт.",2-к. квартира,"44,8 м²",3/5 эт.,5400000,120536,NaN,р-н Кировский,"ул. Гоголя, 61",2 часа назад,Частное лицо,NaN,NaN,NaN,2920724735,tomsk,17,Томск; р-н Кировский; ул. Гоголя; 61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200832,https://www.avito.ru/krasnodar/kvartiry/2-k._k...,"2-к. квартира, 64,2 м², 7/24 эт.",2-к. квартира,"64,2 м²",7/24 эт.,11877000.0,185000.0,"ЖК ""Рекорд"" 2 очередь",р-н Карасунский,"ул. Новороссийская, лит. 2",3 недели назад,Застройщик,"ЖК ""Рекорд"" 2 очередь",https://www.avito.ru/user/9baab164afea22c5cf7a...,NaN,2919396604,krasnodar,2,Краснодар; р-н Карасунский; ул. Новороссийская...
200833,https://www.avito.ru/krasnodar/kvartiry/2-k._k...,"2-к. квартира, 64,2 м², 8/24 эт.",2-к. квартира,"64,2 м²",8/24 эт.,11877000.0,185000.0,"ЖК ""Рекорд"" 2 очередь",р-н Карасунский,"ул. Новороссийская, лит. 2",3 недели назад,Застройщик,"ЖК ""Рекорд"" 2 очередь",https://www.avito.ru/user/9baab164afea22c5cf7a...,NaN,2918873627,krasnodar,2,Краснодар; р-н Карасунский; ул. Новороссийская...
200834,https://www.avito.ru/krasnodar/kvartiry/2-k._k...,"2-к. квартира, 64,2 м², 6/24 эт.",2-к. квартира,"64,2 м²",6/24 эт.,11877000.0,185000.0,"ЖК ""Рекорд"" 2 очередь",р-н Карасунский,"ул. Новороссийская, лит. 2",3 недели назад,Застройщик,"ЖК ""Рекорд"" 2 очередь",https://www.avito.ru/user/9baab164afea22c5cf7a...,NaN,2918970728,krasnodar,2,Краснодар; р-н Карасунский; ул. Новороссийская...
200835,https://www.avito.ru/krasnodar/kvartiry/2-k._k...,"2-к. квартира, 64,2 м², 5/24 эт.",2-к. квартира,"64,2 м²",5/24 эт.,11556000.0,180000.0,"ЖК ""Рекорд"" 2 очередь",р-н Карасунский,"ул. Новороссийская, лит. 2",3 недели назад,Застройщик,"ЖК ""Рекорд"" 2 очередь",https://www.avito.ru/user/9baab164afea22c5cf7a...,NaN,2919298481,krasnodar,2,Краснодар; р-н Карасунский; ул. Новороссийская...
200836,https://www.avito.ru/krasnodar/kvartiry/2-k._k...,"2-к. квартира, 64,2 м², 3/24 эт.",2-к. квартира,"64,2 м²",3/24 эт.,11556000.0,180000.0,"ЖК ""Рекорд"" 2 очередь",р-н Карасунский,"ул. Новороссийская, лит. 2",3 недели назад,Застройщик,"ЖК ""Рекорд"" 2 очередь",https://www.avito.ru/user/9baab164afea22c5cf7a...,NaN,2918860133,krasnodar,2,Краснодар; р-н Карасунский; ул. Новороссийская...

In [40]:
files_avito = sorted(files_avito, key=lambda x: datetime.strptime(x[:8], '%d-%m-%y'))
files_cian = sorted(files_cian, key=lambda x: datetime.strptime(x[5:13], '%d-%m-%y'))

In [24]:
from tqdm import tqdm

In [26]:
# avito
df_avito_compare = pd.DataFrame(columns=['date_new', 'date_pre', 'diff_files_cnt', 'diff_files_rub', 
                                         'diff_total_ad_id_cnt', 'diff_total_ad_id_rub',
                                         'diff_total_addr_cnt', 'diff_total_addr_rub',
                                         'city2rub', 'city3rub', 'city4rub', 'city5rub', 'city6rub', 'city7rub', 'city12rub', 'city17rub',
                                         'city18rub', 'city19rub', 'city20rub'])
city_df, source_df, exc_code = get_tables_info(sql_engine)
diff_list = []
city_df_dict = city_df.set_index('id').to_dict()['url_avito']
for i in tqdm(range(len(files_avito))):
    if i - 1 >=0:
        print('compare ' + files_avito[i], files_avito[i-1])
        test_avito_1 = pd.read_csv('saved_shit/' + files_avito[i], delimiter=';')
        test_avito_1['ad_id'] = test_avito_1['Ссылка'].apply(lambda x: x.split('_')[-1])
        test_avito_1['ad_id'] = test_avito_1['ad_id'].astype('int64')
        test_avito_1['city'] = test_avito_1['Ссылка'].apply(lambda x: x.split('/')[3])
        test_avito_1['city_id'] = test_avito_1['city'].apply(lambda x: city_id_from_link(x, city_df_dict))
        test_avito_1['addr'] = test_avito_1.apply(lambda row: avito_addr_from_row(row, city_df), axis=1)
        
        test_avito_pre = pd.read_csv('saved_shit/' + files_avito[i - 1], delimiter=';')
        test_avito_pre['ad_id'] = test_avito_pre['Ссылка'].apply(lambda x: x.split('_')[-1])
        test_avito_pre['ad_id'] = test_avito_pre['ad_id'].astype('int64')
        test_avito_pre['city'] = test_avito_pre['Ссылка'].apply(lambda x: x.split('/')[3])
        test_avito_pre['city_id'] = test_avito_pre['city'].apply(lambda x: city_id_from_link(x, city_df_dict))
        test_avito_pre['addr'] = test_avito_pre.apply(lambda row: avito_addr_from_row(row, city_df), axis=1)
        
#         diff_ad_id = len(set(test_avito_1.ad_id.to_list()) - set(test_avito_pre.ad_id.to_list()))
#         print(diff_ad_id, 'записей между 2 файлами; в рублях:                       ', diff_ad_id * 0.15)
        
#         diff_all_ad_id = len(set(test_avito_1.ad_id.to_list()) - set(all_ad_id))
#         print(diff_all_ad_id, 'записей между новым файлом и всеми остальными; в рублях: ', diff_all_ad_id * 0.15)
    
        diff_files_cnt = len(set(test_avito_1.ad_id.to_list()) - set(test_avito_pre.ad_id.to_list()))
        diff_files_rub = diff_files_cnt*0.15
        
        diff_total_ad_id_cnt = len(set(test_avito_1.ad_id.to_list()) - set(all_ad_id))
        diff_total_ad_id_rub = diff_total_ad_id_cnt*0.15
        
        diff_total_addr_cnt = len(set(test_avito_1.addr.to_list()) - set(all_addr))
        diff_total_addr_rub = diff_total_addr_cnt*0.15
        
#         city2rub = len(set(test_avito_1[test_avito_1.city_id == 2].ad_id.to_list()) - set(all_ad_id))*0.15
#         city3rub = len(set(test_avito_1[test_avito_1.city_id == 3].ad_id.to_list()) - set(all_ad_id))*0.15
#         city4rub = len(set(test_avito_1[test_avito_1.city_id == 4].ad_id.to_list()) - set(all_ad_id))*0.15
#         city5rub = len(set(test_avito_1[test_avito_1.city_id == 5].ad_id.to_list()) - set(all_ad_id))*0.15
#         city6rub = len(set(test_avito_1[test_avito_1.city_id == 6].ad_id.to_list()) - set(all_ad_id))*0.15
#         city7rub = len(set(test_avito_1[test_avito_1.city_id == 7].ad_id.to_list()) - set(all_ad_id))*0.15
#         city12rub = len(set(test_avito_1[test_avito_1.city_id == 12].ad_id.to_list()) - set(all_ad_id))*0.15
#         city17rub = len(set(test_avito_1[test_avito_1.city_id == 17].ad_id.to_list()) - set(all_ad_id))*0.15
#         city18rub = len(set(test_avito_1[test_avito_1.city_id == 18].ad_id.to_list()) - set(all_ad_id))*0.15
#         city19rub = len(set(test_avito_1[test_avito_1.city_id == 19].ad_id.to_list()) - set(all_ad_id))*0.15
#         city20rub = len(set(test_avito_1[test_avito_1.city_id == 20].ad_id.to_list()) - set(all_ad_id))*0.15

        city2rub = len(set(test_avito_1[test_avito_1.city_id == 2].addr.to_list()) - set(all_addr))*0.15
        city3rub = len(set(test_avito_1[test_avito_1.city_id == 3].addr.to_list()) - set(all_addr))*0.15
        city4rub = len(set(test_avito_1[test_avito_1.city_id == 4].addr.to_list()) - set(all_addr))*0.15
        city5rub = len(set(test_avito_1[test_avito_1.city_id == 5].addr.to_list()) - set(all_addr))*0.15
        city6rub = len(set(test_avito_1[test_avito_1.city_id == 6].addr.to_list()) - set(all_addr))*0.15
        city7rub = len(set(test_avito_1[test_avito_1.city_id == 7].addr.to_list()) - set(all_addr))*0.15
        city12rub = len(set(test_avito_1[test_avito_1.city_id == 12].addr.to_list()) - set(all_addr))*0.15
        city17rub = len(set(test_avito_1[test_avito_1.city_id == 17].addr.to_list()) - set(all_addr))*0.15
        city18rub = len(set(test_avito_1[test_avito_1.city_id == 18].addr.to_list()) - set(all_addr))*0.15
        city19rub = len(set(test_avito_1[test_avito_1.city_id == 19].addr.to_list()) - set(all_addr))*0.15
        city20rub = len(set(test_avito_1[test_avito_1.city_id == 20].addr.to_list()) - set(all_addr))*0.15
        
        to_append = [files_avito[i], files_avito[i-1], diff_files_cnt, diff_files_rub, 
                     diff_total_ad_id_cnt, diff_total_ad_id_rub,
                     diff_total_addr_cnt, diff_total_addr_rub,
                    city2rub, city3rub, city4rub, city5rub, city6rub, city7rub, city12rub, city17rub, city18rub, city19rub, city20rub]
        df_avito_compare.loc[len(df_avito_compare)] = to_append
        
        all_ad_id.extend(test_avito_1.ad_id.to_list())
        all_addr.extend(list(test_avito_1.addr.unique()))
        
        print()
    else: # first file
        test_avito_new = pd.read_csv('saved_shit/' + files_avito[i], delimiter=';')
        test_avito_new['ad_id'] = test_avito_new['Ссылка'].apply(lambda x: x.split('_')[-1])
        test_avito_new['ad_id'] = test_avito_new['ad_id'].astype('int64')
        test_avito_new['city'] = test_avito_new['Ссылка'].apply(lambda x: x.split('/')[3])
        test_avito_new['city_id'] = test_avito_new['city'].apply(lambda x: city_id_from_link(x, city_df_dict))
        test_avito_new['addr'] = test_avito_new.apply(lambda row: avito_addr_from_row(row, city_df), axis=1)
        
        all_ad_id = test_avito_new.ad_id.to_list()
        all_addr = test_avito_new.addr.to_list()
        
        print(files_avito[i], '- все новые: ', len(set(test_avito_new.ad_id.to_list())))
        print()

  4%|███▍                                                                               | 1/24 [00:33<12:52, 33.57s/it]

25-04-23 (без дублей).csv - все новые:  172756

compare 26-04-23 (без дублей).csv 25-04-23 (без дублей).csv

  8%|██████▉                                                                            | 2/24 [01:41<19:44, 53.83s/it]

compare 27-04-23 (без дублей).csv 26-04-23 (без дублей).csv

 12%|██████████▍                                                                        | 3/24 [02:52<21:30, 61.45s/it]

compare 28-04-23 (без дублей).csv 27-04-23 (без дублей).csv

 17%|█████████████▊                                                                     | 4/24 [04:08<22:27, 67.40s/it]

compare 29-04-23 (без дублей).csv 28-04-23 (без дублей).csv

 21%|█████████████████▎                                                                 | 5/24 [05:27<22:41, 71.65s/it]

compare 30-04-23 (без дублей).csv 29-04-23 (без дублей).csv

 25%|████████████████████▊                                                              | 6/24 [06:44<22:00, 73.38s/it]

compare 01-05-23 (без дублей).csv 30-04-23 (без дублей).csv

 29%|████████████████████████▏                                                          | 7/24 [08:00<20:59, 74.07s/it]

compare 02-05-23 (без дублей).csv 01-05-23 (без дублей).csv

 33%|███████████████████████████▋                                                       | 8/24 [09:15<19:51, 74.47s/it]

compare 03-05-23 (без дублей).csv 02-05-23 (без дублей).csv

 38%|███████████████████████████████▏                                                   | 9/24 [10:31<18:46, 75.08s/it]

compare 04-05-23 (без дублей).csv 03-05-23 (без дублей).csv

 42%|██████████████████████████████████▏                                               | 10/24 [11:47<17:35, 75.42s/it]

compare 05-05-23 (без дублей).csv 04-05-23 (без дублей).csv

 46%|█████████████████████████████████████▌                                            | 11/24 [13:03<16:22, 75.61s/it]

compare 06-05-23 (без дублей).csv 05-05-23 (без дублей).csv

 50%|█████████████████████████████████████████                                         | 12/24 [14:21<15:12, 76.07s/it]

compare 07-05-23 (без дублей).csv 06-05-23 (без дублей).csv

 54%|████████████████████████████████████████████▍                                     | 13/24 [15:37<13:56, 76.07s/it]

compare 08-05-23 (без дублей).csv 07-05-23 (без дублей).csv

 58%|███████████████████████████████████████████████▊                                  | 14/24 [16:57<12:54, 77.42s/it]

compare 09-05-23 (без дублей).csv 08-05-23 (без дублей).csv

 62%|███████████████████████████████████████████████████▎                              | 15/24 [18:20<11:50, 78.97s/it]

compare 10-05-23 (без дублей).csv 09-05-23 (без дублей).csv

 67%|██████████████████████████████████████████████████████▋                           | 16/24 [19:36<10:25, 78.19s/it]

compare 11-05-23 (без дублей).csv 10-05-23 (без дублей).csv

 71%|██████████████████████████████████████████████████████████                        | 17/24 [20:51<09:00, 77.28s/it]

compare 12-05-23 (без дублей).csv 11-05-23 (без дублей).csv

 75%|█████████████████████████████████████████████████████████████▌                    | 18/24 [22:03<07:33, 75.56s/it]

compare 13-05-23 (без дублей).csv 12-05-23 (без дублей).csv

 79%|████████████████████████████████████████████████████████████████▉                 | 19/24 [23:14<06:11, 74.36s/it]

compare 14-05-23 (без дублей).csv 13-05-23 (без дублей).csv

 83%|████████████████████████████████████████████████████████████████████▎             | 20/24 [24:27<04:55, 73.78s/it]

compare 15-05-23 (без дублей).csv 14-05-23 (без дублей).csv

 88%|███████████████████████████████████████████████████████████████████████▊          | 21/24 [25:37<03:38, 72.75s/it]

compare 16-05-23 (без дублей).csv 15-05-23 (без дублей).csv

 92%|███████████████████████████████████████████████████████████████████████████▏      | 22/24 [26:53<02:27, 73.70s/it]

compare 17-05-23 (без дублей).csv 16-05-23 (без дублей).csv

 96%|██████████████████████████████████████████████████████████████████████████████▌   | 23/24 [28:13<01:15, 75.40s/it]

compare 18-05-23 (без дублей).csv 17-05-23 (без дублей).csv

100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [29:33<00:00, 73.88s/it]

In [34]:
df_avito_compare

,date_new,date_pre,diff_files_cnt,diff_files_rub,diff_total_ad_id_cnt,diff_total_ad_id_rub,diff_total_addr_cnt,diff_total_addr_rub,city2rub,city3rub,city4rub,city5rub,city6rub,city7rub,city12rub,city17rub,city18rub,city19rub,city20rub
0,26-04-23 (без дублей).csv,25-04-23 (без дублей).csv,18960,2844.00,18960,2844.00,3155,473.25,49.95,41.10,32.10,12.75,1.95,87.30,22.35,32.25,28.50,70.95,94.05
1,27-04-23 (без дублей).csv,26-04-23 (без дублей).csv,12043,1806.45,6829,1024.35,1055,158.25,34.95,24.90,6.60,3.30,5.55,24.30,11.70,6.30,9.75,8.85,22.05
2,28-04-23 (без дублей).csv,27-04-23 (без дублей).csv,25723,3858.45,16228,2434.20,955,143.25,14.10,14.40,9.30,1.65,1.50,26.10,21.45,10.65,23.40,4.20,16.50
3,29-04-23 (без дублей).csv,28-04-23 (без дублей).csv,19246,2886.90,6237,935.55,502,75.30,14.70,15.15,0.90,1.20,1.50,2.40,2.25,7.95,7.20,4.20,17.85
4,30-04-23 (без дублей).csv,29-04-23 (без дублей).csv,13862,2079.30,2453,367.95,460,69.00,27.30,6.60,2.10,1.65,0.60,5.10,9.15,2.25,6.30,1.95,6.00
5,01-05-23 (без дублей).csv,30-04-23 (без дублей).csv,17128,2569.20,2397,359.55,510,76.50,9.30,27.90,3.75,4.35,0.60,5.10,4.20,2.70,3.90,3.00,11.70
6,02-05-23 (без дублей).csv,01-05-23 (без дублей).csv,21430,3214.50,3324,498.60,779,116.85,20.10,16.20,2.10,0.45,1.20,10.80,14.70,1.65,17.40,11.55,20.70
7,03-05-23 (без дублей).csv,02-05-23 (без дублей).csv,19807,2971.05,3982,597.30,705,105.75,13.95,17.10,4.80,1.95,1.95,7.95,10.95,8.40,17.40,4.20,17.10
8,04-05-23 (без дублей).csv,03-05-23 (без дублей).csv,18613,2791.95,3507,526.05,818,122.70,31.20,18.90,4.35,1.05,1.05,11.70,22.20,2.25,9.90,8.25,11.85
9,05-05-23 (без дублей).csv,04-05-23 (без дублей).csv,22163,3324.45,5314,797.10,814,122.10,21.90,9.45,5.40,3.90,0.90,8.70,7.50,5.10,6.75,8.25,11.70
10,06-05-23 (без дублей).csv,05-05-23 (без дублей).csv,18727,2809.05,2664,399.60,354,53.10,3.15,9.30,6.00,1.20,3.00,5.40,6.60,1.95,3.60,2.55,10.35
11,07-05-23 (без дублей).csv,06-05-23 (без дублей).csv,12720,1908.00,1995,299.25,387,58.05,3.60,10.20,1.35,0.30,0.30,11.70,7.05,1.35,3.00,7.65,11.55
12,08-05-23 (без дублей).csv,07-05-23 (без дублей).csv,12548,1882.20,1707,256.05,428,64.20,10.65,15.15,0.30,1.35,1.65,3.60,2.10,1.65,12.15,3.00,12.60
13,09-05-23 (без дублей).csv,08-05-23 (без дублей).csv,11101,1665.15,1473,220.95,216,32.40,4.95,8.70,0.90,0.90,0.15,7.20,3.00,0.15,1.95,1.65,2.85
14,10-05-23 (без дублей).csv,09-05-23 (без дублей).csv,15978,2396.70,2269,340.35,493,73.95,17.55,8.25,4.35,0.30,1.35,3.15,13.65,2.70,8.70,7.20,6.75
15,11-05-23 (без дублей).csv,10-05-23 (без дублей).csv,20877,3131.55,3161,474.15,814,122.10,26.25,19.65,1.95,1.35,0.75,19.80,9.15,2.25,16.35,15.60,9.00
16,12-05-23 (без дублей).csv,11-05-23 (без дублей).csv,24408,3661.20,6426,963.90,492,73.80,18.00,7.65,4.05,0.90,0.45,7.95,11.55,1.35,13.05,3.75,5.10
17,13-05-23 (без дублей).csv,12-05-23 (без дублей).csv,16330,2449.50,2616,392.40,376,56.40,12.30,5.85,4.50,1.05,0.60,3.90,3.45,0.30,10.35,9.60,4.50
18,14-05-23 (без дублей).csv,13-05-23 (без дублей).csv,14482,2172.30,1847,277.05,275,41.25,6.15,12.15,1.05,1.20,2.25,3.15,4.05,1.95,3.00,2.85,3.45
19,15-05-23 (без дублей).csv,14-05-23 (без дублей).csv,19829,2974.35,1987,298.05,423,63.45,6.60,18.75,3.00,2.70,0.75,5.55,10.95,2.55,6.75,1.80,4.05
20,16-05-23 (без дублей).csv,15-05-23 (без дублей).csv,31226,4683.90,6067,910.05,616,92.40,13.65,9.45,0.75,1.05,0.30,13.65,9.00,2.25,15.75,11.70,14.85
21,17-05-23 (без дублей).csv,16-05-23 (без дублей).csv,18764,2814.60,3444,516.60,492,73.80,14.40,25.80,1.80,0.75,1.05,2.85,9.60,1.35,7.20,3.00,6.00
22,18-05-23 (без дублей).csv,17-05-23 (без дублей).csv,20983,3147.45,3397,509.55,464,69.60,11.10,10.50,1.65,0.60,0.90,6.60,16.05,2.25,10.95,1.95,7.05

In [43]:
# cian
df_cian_compare = pd.DataFrame(columns=['date_new', 'date_pre', 'diff_files_cnt', 
                                        'diff_files_rub', 'diff_total_ad_id_cnt', 'diff_total_ad_id_rub', 
                                        'diff_total_addr_cnt', 'diff_total_addr_rub',
                                         'city2rub', 'city3rub', 'city4rub', 'city5rub', 'city6rub', 'city7rub', 'city12rub', 'city17rub',
                                         'city18rub', 'city19rub', 'city20rub'])
city_df, source_df, exc_code = get_tables_info(sql_engine)
diff_list = []
city_df_dict = city_df.set_index('id').to_dict()['name']
for i in range(len(files_cian)):
    if i - 1 >=0:
        print('compare ' + files_cian[i], files_cian[i-1])
        test_cian_1 = pd.read_csv('saved_shit/' + files_cian[i], delimiter=',')
        test_cian_1['ad_id'] = test_cian_1['Ссылка'].apply(lambda x: x.split('/')[-2])
        test_cian_1['ad_id'] = test_cian_1['ad_id'].astype('int64')
        test_cian_1['city'] = test_cian_1['Адрес'].apply(lambda x: x.split(';')[1])
        test_cian_1['city_id'] = test_cian_1['city'].apply(lambda x: city_id_from_link(x, city_df_dict))
        test_cian_1['addr'] = test_cian_1['Адрес']

        test_cian_pre = pd.read_csv('saved_shit/' + files_cian[i - 1], delimiter=',')
        test_cian_pre['ad_id'] = test_cian_pre['Ссылка'].apply(lambda x: x.split('/')[-2])
        test_cian_pre['ad_id'] = test_cian_pre['ad_id'].astype('int64')
        test_cian_pre['city'] = test_cian_pre['Адрес'].apply(lambda x: x.split(';')[1])
        test_cian_pre['city_id'] = test_cian_pre['city'].apply(lambda x: city_id_from_link(x, city_df_dict))
        test_cian_pre['addr'] = test_cian_pre['Адрес']

#         diff_ad_id = len(set(test_cian_1.ad_id.to_list()) - set(test_cian_pre.ad_id.to_list()))
#         print(diff_ad_id, 'записей между 2 файлами; в рублях:                       ', diff_ad_id * 0.15)
        
#         diff_all_ad_id = len(set(test_cian_1.ad_id.to_list()) - set(all_ad_id))
#         print(diff_all_ad_id, 'записей между новым файлом и всеми остальными; в рублях: ', diff_all_ad_id * 0.15)
    
        diff_files_cnt = len(set(test_cian_1.ad_id.to_list()) - set(test_avito_pre.ad_id.to_list()))
        diff_files_rub = diff_files_cnt*0.15
        
        diff_total_ad_id_cnt = len(set(test_cian_1.ad_id.to_list()) - set(all_ad_id))
        diff_total_ad_id_rub = diff_total_ad_id_cnt*0.15
        
        diff_total_addr_cnt = len(set(test_cian_1.addr.to_list()) - set(all_addr))
        diff_total_addr_rub = diff_total_addr_cnt*0.15
        
#         city2rub = len(set(test_cian_1[test_cian_1.city_id == 2.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city3rub = len(set(test_cian_1[test_cian_1.city_id == 3.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city4rub = len(set(test_cian_1[test_cian_1.city_id == 4.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city5rub = len(set(test_cian_1[test_cian_1.city_id == 5.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city6rub = len(set(test_cian_1[test_cian_1.city_id == 6.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city7rub = len(set(test_cian_1[test_cian_1.city_id == 7.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city12rub = len(set(test_cian_1[test_cian_1.city_id == 12.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city17rub = len(set(test_cian_1[test_cian_1.city_id == 17.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city18rub = len(set(test_cian_1[test_cian_1.city_id == 18.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city19rub = len(set(test_cian_1[test_cian_1.city_id == 19.0].ad_id.to_list()) - set(all_ad_id))*0.15
#         city20rub = len(set(test_cian_1[test_cian_1.city_id == 20.0].ad_id.to_list()) - set(all_ad_id))*0.15

        city2rub = len(set(test_cian_1[test_cian_1.city_id == 2.0].addr.to_list()) - set(all_addr))*0.15
        city3rub = len(set(test_cian_1[test_cian_1.city_id == 3.0].addr.to_list()) - set(all_addr))*0.15
        city4rub = len(set(test_cian_1[test_cian_1.city_id == 4.0].addr.to_list()) - set(all_addr))*0.15
        city5rub = len(set(test_cian_1[test_cian_1.city_id == 5.0].addr.to_list()) - set(all_addr))*0.15
        city6rub = len(set(test_cian_1[test_cian_1.city_id == 6.0].addr.to_list()) - set(all_addr))*0.15
        city7rub = len(set(test_cian_1[test_cian_1.city_id == 7.0].addr.to_list()) - set(all_addr))*0.15
        city12rub = len(set(test_cian_1[test_cian_1.city_id == 12.0].addr.to_list()) - set(all_addr))*0.15
        city17rub = len(set(test_cian_1[test_cian_1.city_id == 17.0].addr.to_list()) - set(all_addr))*0.15
        city18rub = len(set(test_cian_1[test_cian_1.city_id == 18.0].addr.to_list()) - set(all_addr))*0.15
        city19rub = len(set(test_cian_1[test_cian_1.city_id == 19.0].addr.to_list()) - set(all_addr))*0.15
        city20rub = len(set(test_cian_1[test_cian_1.city_id == 20.0].addr.to_list()) - set(all_addr))*0.15
        
        to_append = [files_cian[i], files_cian[i-1], diff_files_cnt, diff_files_rub, 
                     diff_total_ad_id_cnt, diff_total_ad_id_rub,
                     diff_total_addr_cnt, diff_total_addr_rub,
                    city2rub, city3rub, city4rub, city5rub, city6rub, city7rub, city12rub, city17rub, city18rub, city19rub, city20rub]
        df_cian_compare.loc[len(df_cian_compare)] = to_append
        
        all_ad_id.extend(test_cian_1.ad_id.to_list())
        all_addr.extend(list(test_cian_1.addr.unique()))
        print()
    else: # first file
        test_cian_new = pd.read_csv('saved_shit/' + files_cian[i], delimiter=',')
        test_cian_new['ad_id'] = test_cian_new['Ссылка'].apply(lambda x: x.split('/')[-2])
        test_cian_new['ad_id'] = test_cian_new['ad_id'].astype('int64')
        test_cian_new['addr'] = test_cian_new['Адрес']
        
        all_ad_id = test_cian_new.ad_id.to_list()
        all_addr = test_cian_new.addr.to_list()
        
        print('первый файл - все новые: ', len(set(test_avito_new.ad_id.to_list())))
        print()

первый файл - все новые:  172756

compare циан 26-04-23 (без дублей).csv циан 25-04-23 (без дублей).csv

compare циан 27-04-23 (без дублей).csv циан 26-04-23 (без дублей).csv

compare циан 28-04-23 (без дублей).csv циан 27-04-23 (без дублей).csv

compare циан 29-04-23 (без дублей).csv циан 28-04-23 (без дублей).csv

compare циан 30-04-23 (без дублей).csv циан 29-04-23 (без дублей).csv

compare циан 01-05-23 (без дублей).csv циан 30-04-23 (без дублей).csv

compare циан 02-05-23 (без дублей).csv циан 01-05-23 (без дублей).csv

compare циан 03-05-23 (без дублей).csv циан 02-05-23 (без дублей).csv

compare циан 04-05-23 (без дублей).csv циан 03-05-23 (без дублей).csv

compare циан 05-05-23 (без дублей).csv циан 04-05-23 (без дублей).csv

compare циан 06-05-23 (без дублей).csv циан 05-05-23 (без дублей).csv

compare циан 07-05-23 (без дублей).csv циан 06-05-23 (без дублей).csv

compare циан 08-05-23 (без дублей).csv циан 07-05-23 (без дублей).csv

compare циан 09-05-23 (без дублей).csv циан 08-05-23 (без дублей).csv

compare циан 10-05-23 (без дублей).csv циан 09-05-23 (без дублей).csv

compare циан 11-05-23 (без дублей).csv циан 10-05-23 (без дублей).csv

compare циан 12-05-23 (без дублей).csv циан 11-05-23 (без дублей).csv

compare циан 13-05-23 (без дублей).csv циан 12-05-23 (без дублей).csv

compare циан 14-05-23 (без дублей).csv циан 13-05-23 (без дублей).csv

compare циан 15-05-23 (без дублей).csv циан 14-05-23 (без дублей).csv

compare циан 16-05-23 (без дублей).csv циан 15-05-23 (без дублей).csv

compare циан 17-05-23 (без дублей).csv циан 16-05-23 (без дублей).csv

compare циан 18-05-23 (без дублей).csv циан 17-05-23 (без дублей).csv

compare циан 19-05-23 (без дублей).csv циан 18-05-23 (без дублей).csv

In [45]:
df_cian_compare

,date_new,date_pre,diff_files_cnt,diff_files_rub,diff_total_ad_id_cnt,diff_total_ad_id_rub,diff_total_addr_cnt,diff_total_addr_rub,city2rub,city3rub,city4rub,city5rub,city6rub,city7rub,city12rub,city17rub,city18rub,city19rub,city20rub
0,циан 26-04-23 (без дублей).csv,циан 25-04-23 (без дублей).csv,100123,15018.45,5751,862.65,490,73.50,6.15,7.20,1.50,1.95,0.75,12.15,16.05,0.15,17.25,5.25,3.60
1,циан 27-04-23 (без дублей).csv,циан 26-04-23 (без дублей).csv,126181,18927.15,9316,1397.40,461,69.15,6.45,5.25,1.20,0.75,0.45,7.35,13.80,5.85,15.75,6.60,3.75
2,циан 28-04-23 (без дублей).csv,циан 27-04-23 (без дублей).csv,121725,18258.75,4697,704.55,281,42.15,2.40,6.30,0.45,0.75,0.15,3.90,8.25,0.90,10.20,2.10,1.95
3,циан 29-04-23 (без дублей).csv,циан 28-04-23 (без дублей).csv,122191,18328.65,2538,380.70,171,25.65,2.85,3.00,0.75,0.30,0.00,4.35,5.10,0.90,3.90,0.60,1.50
4,циан 30-04-23 (без дублей).csv,циан 29-04-23 (без дублей).csv,123234,18485.10,1672,250.80,129,19.35,1.20,1.05,0.60,0.15,0.00,1.80,3.90,0.75,4.05,1.95,0.60
5,циан 01-05-23 (без дублей).csv,циан 30-04-23 (без дублей).csv,117296,17594.40,2592,388.80,133,19.95,1.35,3.60,0.30,0.15,0.15,1.35,2.25,2.55,4.65,0.90,0.90
6,циан 02-05-23 (без дублей).csv,циан 01-05-23 (без дублей).csv,121540,18231.00,3854,578.10,290,43.50,3.15,4.65,1.20,0.30,0.15,4.05,6.75,3.00,13.50,2.55,1.50
7,циан 03-05-23 (без дублей).csv,циан 02-05-23 (без дублей).csv,121495,18224.25,6076,911.40,358,53.70,3.90,5.55,2.10,0.75,0.30,6.60,8.70,3.45,13.35,3.45,1.65
8,циан 04-05-23 (без дублей).csv,циан 03-05-23 (без дублей).csv,121164,18174.60,4198,629.70,314,47.10,3.75,7.05,0.75,0.60,0.30,3.00,8.85,1.80,9.45,3.90,3.75
9,циан 05-05-23 (без дублей).csv,циан 04-05-23 (без дублей).csv,124128,18619.20,5107,766.05,278,41.70,3.75,3.30,0.45,0.15,0.15,3.75,6.75,1.95,13.20,1.80,3.30
10,циан 06-05-23 (без дублей).csv,циан 05-05-23 (без дублей).csv,126112,18916.80,2257,338.55,358,53.70,1.95,2.55,0.00,0.15,0.30,1.20,4.05,0.60,36.90,1.80,1.80
11,циан 07-05-23 (без дублей).csv,циан 06-05-23 (без дублей).csv,123421,18513.15,1495,224.25,126,18.90,0.75,1.05,0.30,0.30,0.15,1.80,3.00,1.05,6.00,1.35,1.50
12,циан 08-05-23 (без дублей).csv,циан 07-05-23 (без дублей).csv,125312,18796.80,2341,351.15,126,18.90,2.10,3.45,0.75,0.00,0.00,1.50,3.75,0.45,3.15,1.20,0.90
13,циан 09-05-23 (без дублей).csv,циан 08-05-23 (без дублей).csv,123728,18559.20,1333,199.95,81,12.15,1.50,0.90,0.15,0.30,0.15,0.30,2.25,0.30,2.40,1.50,1.50
14,циан 10-05-23 (без дублей).csv,циан 09-05-23 (без дублей).csv,119791,17968.65,2993,448.95,261,39.15,3.00,4.05,0.75,0.75,0.15,3.75,5.40,1.80,12.90,2.55,1.95
15,циан 11-05-23 (без дублей).csv,циан 10-05-23 (без дублей).csv,119379,17906.85,3211,481.65,248,37.20,3.15,4.20,0.45,0.30,0.30,2.40,7.80,1.95,10.05,3.00,2.10
16,циан 12-05-23 (без дублей).csv,циан 11-05-23 (без дублей).csv,119144,17871.60,4422,663.30,265,39.75,2.85,3.90,1.35,0.45,0.45,3.75,6.15,2.10,9.60,3.45,2.85
17,циан 13-05-23 (без дублей).csv,циан 12-05-23 (без дублей).csv,116837,17525.55,2159,323.85,157,23.55,2.70,2.40,0.15,0.00,0.30,3.30,4.80,0.30,4.65,2.25,0.90
18,циан 14-05-23 (без дублей).csv,циан 13-05-23 (без дублей).csv,119293,17893.95,1139,170.85,88,13.20,0.75,1.05,0.15,0.15,0.15,1.80,1.80,0.75,2.40,0.60,0.90
19,циан 15-05-23 (без дублей).csv,циан 14-05-23 (без дублей).csv,115487,17323.05,3443,516.45,239,35.85,2.40,1.95,0.75,0.00,0.30,3.75,6.75,0.45,12.75,3.30,2.40
20,циан 16-05-23 (без дублей).csv,циан 15-05-23 (без дублей).csv,118801,17820.15,4122,618.30,260,39.00,2.25,6.30,0.45,0.30,0.75,4.35,5.10,1.50,9.60,3.15,3.45
21,циан 17-05-23 (без дублей).csv,циан 16-05-23 (без дублей).csv,121123,18168.45,4824,723.60,241,36.15,3.60,2.55,0.60,0.90,0.00,2.70,5.55,2.25,10.05,2.25,3.45
22,циан 18-05-23 (без дублей).csv,циан 17-05-23 (без дублей).csv,120169,18025.35,3881,582.15,202,30.30,4.05,3.00,1.05,0.15,0.00,2.40,6.00,0.60,7.80,1.65,2.70
23,циан 19-05-23 (без дублей).csv,циан 18-05-23 (без дублей).csv,117448,17617.20,3252,487.80,227,34.05,4.65,1.65,0.60,1.05,0.00,3.45,6.30,0.45,8.85,1.50,3.90

In [86]:
df_cian_compare

,date_new,date_pre,diff_files_cnt,diff_files_rub,diff_total_ad_id_cnt,diff_total_ad_id_rub,city2rub,city3rub,city4rub,city5rub,city6rub,city7rub,city12rub,city17rub,city18rub,city19rub,city20rub
0,циан 16-04-23 (без дублей) new.csv,циан 15-04-23 (без дублей) new.csv,80615,12092.25,2906,435.90,333.15,0.00,10.80,7.20,2.40,26.25,42.90,8.25,0.00,0.00,0.00
1,циан 17-04-23 (без дублей) new.csv,циан 16-04-23 (без дублей) new.csv,79701,11955.15,3047,457.05,312.90,0.00,15.75,22.50,1.35,40.80,45.15,17.70,0.00,0.00,0.00
2,циан 18-04-23 (без дублей).csv,циан 17-04-23 (без дублей) new.csv,89784,13467.60,28697,4304.55,584.70,3562.05,29.85,19.95,1.80,29.85,51.60,23.55,0.00,0.00,0.00
3,циан 19-04-23 (без дублей).csv,циан 18-04-23 (без дублей).csv,89188,13378.20,4318,647.70,402.30,97.95,15.90,18.30,1.35,35.10,53.25,21.15,0.00,0.00,0.00
4,циан 20-04-23 (без дублей).csv,циан 19-04-23 (без дублей).csv,88600,13290.00,3487,523.05,325.50,80.10,13.35,11.55,1.65,25.35,38.55,25.65,0.00,0.00,0.00
5,циан 21-04-23 (без дублей).csv,циан 20-04-23 (без дублей).csv,89813,13471.95,3684,552.60,355.50,70.80,18.15,19.35,0.60,25.05,41.55,19.05,0.00,0.00,0.00
6,циан 22-04-23 (без дублей).csv,циан 21-04-23 (без дублей).csv,101236,15185.40,13375,2006.25,153.15,31.35,10.35,9.60,0.60,17.25,23.85,5.70,0.00,744.45,1006.80
7,циан 23-04-23 (без дублей).csv,циан 22-04-23 (без дублей).csv,100575,15086.25,1520,228.00,105.45,15.90,3.15,9.60,0.60,13.35,16.80,3.30,0.00,10.50,46.65
8,циан 25-04-23 (без дублей).csv,циан 23-04-23 (без дублей).csv,126440,18966.00,29116,4367.40,242.85,119.55,22.65,32.55,1.05,37.65,62.10,20.55,3380.40,71.70,370.65
9,циан 26-04-23 (без дублей).csv,циан 25-04-23 (без дублей).csv,100123,15018.45,4101,615.15,107.85,66.90,20.70,22.95,1.50,33.45,43.50,0.15,217.80,51.15,47.40
10,циан 27-04-23 (без дублей).csv,циан 26-04-23 (без дублей).csv,126181,18927.15,6000,900.00,490.05,54.30,19.50,19.05,0.75,28.20,60.30,28.05,116.70,27.75,53.10
11,циан 28-04-23 (без дублей).csv,циан 27-04-23 (без дублей).csv,121725,18258.75,3569,535.35,182.85,63.75,10.35,20.85,0.75,27.60,32.40,8.55,127.05,22.50,32.55
12,циан 29-04-23 (без дублей).csv,циан 28-04-23 (без дублей).csv,122191,18328.65,1963,294.45,116.85,38.85,6.75,11.55,0.15,11.85,20.40,6.90,44.10,8.40,25.20
13,циан 30-04-23 (без дублей).csv,циан 29-04-23 (без дублей).csv,123234,18485.10,1300,195.00,83.10,14.70,5.70,5.55,0.30,5.70,16.35,3.45,35.70,4.95,16.20
14,циан 01-05-23 (без дублей).csv,циан 30-04-23 (без дублей).csv,117296,17594.40,2017,302.55,113.40,55.95,7.20,6.30,0.45,8.85,19.05,17.55,43.50,6.60,21.75
15,циан 02-05-23 (без дублей).csv,циан 01-05-23 (без дублей).csv,121540,18231.00,3261,489.15,187.80,61.95,16.50,14.55,1.05,18.00,21.60,18.30,104.25,13.05,27.75
16,циан 03-05-23 (без дублей).csv,циан 02-05-23 (без дублей).csv,121495,18224.25,4933,739.95,357.30,75.00,29.85,19.80,0.75,30.30,45.60,27.60,100.35,16.35,32.70
17,циан 04-05-23 (без дублей).csv,циан 03-05-23 (без дублей).csv,121164,18174.60,3506,525.90,206.25,70.20,14.10,24.30,1.05,18.45,33.15,19.05,82.35,20.40,31.65
18,циан 05-05-23 (без дублей).csv,циан 04-05-23 (без дублей).csv,124128,18619.20,4530,679.50,368.70,57.45,14.40,20.55,0.45,25.20,33.15,16.20,81.60,12.75,45.60
19,циан 06-05-23 (без дублей).csv,циан 05-05-23 (без дублей).csv,126112,18916.80,1874,281.10,149.85,20.25,6.90,4.80,0.30,7.50,20.10,6.90,32.40,9.45,19.05
20,циан 07-05-23 (без дублей).csv,циан 06-05-23 (без дублей).csv,123421,18513.15,1258,188.70,88.05,20.85,5.85,6.90,0.90,8.10,12.00,4.20,20.85,7.20,11.25
21,циан 08-05-23 (без дублей).csv,циан 07-05-23 (без дублей).csv,125312,18796.80,2054,308.10,134.10,57.90,8.25,9.30,0.30,12.30,24.30,6.00,29.40,7.80,16.05
22,циан 09-05-23 (без дублей).csv,циан 08-05-23 (без дублей).csv,123728,18559.20,1147,172.05,68.55,39.15,2.55,3.15,0.30,10.20,12.60,2.85,18.60,4.65,7.35

In [46]:
df_cian_compare.to_excel('cian_money_new.xlsx')

In [47]:
df_avito_compare.to_excel('avito_money_new.xlsx')